FLAGS = {
    "Algeria": "🇩🇿",
    "Argentina": "🇦🇷",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Belgium": "🇧🇪",
    "Bosnia-Herzegovina": "🇧🇦",
    "Brazil": "🇧🇷",
    "Canada": "🇨🇦",
    "Cape Verde Islands": "🇨🇻",
    "Colombia": "🇨🇴",
    "Congo DR": "🇨🇩",
    "Croatia": "🇭🇷",
    "Curaçao": "🇨🇼",
    "Czechia": "🇨🇿",
    "Ecuador": "🇪🇨",
    "Egypt": "🇪🇬",
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "France": "🇫🇷",
    "Germany": "🇩🇪",
    "Ghana": "🇬🇭",
    "Haiti": "🇭🇹",
    "Iran": "🇮🇷",
    "Iraq": "🇮🇶",
    "Ivory Coast": "🇨🇮",
    "Japan": "🇯🇵",
    "Jordan": "🇯🇴",
    "Mexico": "🇲🇽",
    "Morocco": "🇲🇦",
    "Netherlands": "🇳🇱",
    "New Zealand": "🇳🇿",
    "Norway": "🇳🇴",
    "Panama": "🇵🇦",
    "Paraguay": "🇵🇾",
    "Portugal": "🇵🇹",
    "Qatar": "🇶🇦",
    "Saudi Arabia": "🇸🇦",
    "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Senegal": "🇸🇳",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    "Spain": "🇪🇸",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Tunisia": "🇹🇳",
    "Turkey": "🇹🇷",
    "United States": "🇺🇸",
    "Uruguay": "🇺🇾",
    "Uzbekistan": "🇺🇿"
}

WC_TEAMS = list(FLAGS.keys())

TEAM_ACRONYMS = {
    "alg": "Algeria",
    "arg": "Argentina",
    "aus": "Australia",
    "aut": "Austria",
    "bel": "Belgium",
    "bih": "Bosnia-Herzegovina",
    "bra": "Brazil",
    "can": "Canada",
    "cpv": "Cape Verde Islands",
    "col": "Colombia",
    "cod": "Congo DR",
    "cro": "Croatia",
    "cur": "Curaçao",
    "cze": "Czechia",
    "ecu": "Ecuador",
    "egy": "Egypt",
    "eng": "England",
    "fra": "France",
    "ger": "Germany",
    "gha": "Ghana",
    "hai": "Haiti",
    "iri": "Iran",
    "irq": "Iraq",
    "civ": "Ivory Coast",
    "jpn": "Japan",
    "jor": "Jordan",
    "mex": "Mexico",
    "mor": "Morocco",
    "ned": "Netherlands",
    "nzl": "New Zealand",
    "nor": "Norway",
    "pan": "Panama",
    "par": "Paraguay",
    "por": "Portugal",
    "qat": "Qatar",
    "ksa": "Saudi Arabia",
    "sco": "Scotland",
    "sen": "Senegal",
    "rsa": "South Africa",
    "kor": "South Korea",
    "esp": "Spain",
    "swe": "Sweden",
    "sui": "Switzerland",
    "tun": "Tunisia",
    "tur": "Turkey",
    "usa": "United States",
    "uru": "Uruguay",
    "uzb": "Uzbekistan"
}
